source: clear
services:
  alist:
    image: 'xhofe/alist:latest-aio'
    container_name: alist
    volumes:
      - './data:/opt/alist/data'
    ports:
      - 5244:5244
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
